version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11

  pre_build:
    commands:
      - echo "Installing dependencies, if any"

  build:
    commands:
      - echo "Building and running Glue jobs"
      # Execute the modified Bash script to create and run Glue jobs
      - chmod +x glue_jobs_executer_raw.sh
      - ./glue_jobs_executer_raw.sh

