AWSTemplateFormatVersion: 2010-09-09
Transform: "AWS::LanguageExtensions"
# Sample YAML to demonstrate creating a job using a ORACLE JDBC DB with the viamericas data to an S3 file
#
#
# Mappings
# here we define some required data for glue jobs and glue crawlers
Mappings:
  # GlueObjects
  GlueObjects:
    IntermediateReceiver:
      JobName: "gj_stage_intermediate_receiver"
      ScriptLocation: "s3://viamericas-datalake-dev-us-east-1-283731589572-glue-jobs/stage/intermediate/gjdev_stage_intermediate_receiver_glue_script.py"
      CrawlerName: "crw_stage_intermediate_receiver"
      Path: "s3://viamericas-datalake-dev-us-east-1-283731589572-stage/intermediate_receiver"
      StateMachineName: "sm_stage_intermediate_receiver"
    IntermediateCheckTable:
      JobName: "gj_stage_intermediate_checktable"
      ScriptLocation: "s3://viamericas-datalake-dev-us-east-1-283731589572-glue-jobs/stage/intermediate/gjdev_stage_intermediate_checktable_glue_script.py"
      CrawlerName: "crw_stage_intermediate_checktable"
      Path: "s3://viamericas-datalake-dev-us-east-1-283731589572-stage/intermediate_checktable"
      StateMachineName: "sm_stage_intermediate_checktable"
    IntermediateSender:
      JobName: "gj_stage_intermediate_sender"
      ScriptLocation: "s3://viamericas-datalake-dev-us-east-1-283731589572-glue-jobs/stage/intermediate/gjdev_stage_intermediate_sender_glue_script.py"
      CrawlerName: "crw_stage_intermediate_sender"
      Path: "s3://viamericas-datalake-dev-us-east-1-283731589572-stage/intermediate_sender"
      StateMachineName: "sm_stage_intermediate_sender"
    IntermediateAccountingSubmitTransaction:
      JobName: "gj_stage_intermediate_accounting_submittransaction"
      ScriptLocation: "s3://viamericas-datalake-dev-us-east-1-283731589572-glue-jobs/stage/intermediate/gjdev_stage_intermediate_accounting_submittransaction_glue_script.py"
      CrawlerName: "crw_stage_intermediate_accounting_submittransaction"
      Path: "s3://viamericas-datalake-dev-us-east-1-283731589572-stage/intermediate_accounting_submittransaction"
      StateMachineName: "sm_stage_intermediate_accounting_submittransaction"
    IntermediateVcwBillPaymentsales:
      JobName: "gj_stage_intermediate_vcw_billpayment_sales"
      ScriptLocation: "s3://viamericas-datalake-dev-us-east-1-283731589572-glue-jobs/stage/intermediate/gjdev_stage_intermediate_vcw_billpayment_sales_glue_script.py"
      CrawlerName: "crw_stage_intermediate_vcw_billpayment_sales"
      Path: "s3://viamericas-datalake-dev-us-east-1-283731589572-stage/intermediate_vcw_billpayment_sales"
      StateMachineName: "sm_stage_intermediate_vcw_billpayment_sales"
    IntermediateComisionAgentModoPagoGrupo:
      JobName: "gj_stage_intermediate_comision_agent_modo_pago_grupo"
      ScriptLocation: "s3://viamericas-datalake-dev-us-east-1-283731589572-glue-jobs/stage/intermediate/gjdev_stage_intermediate_comision_agent_modo_pago_grupo_glue_script.py"
      CrawlerName: "crw_stage_intermediate_comision_agent_modo_pago_grupo"
      Path: "s3://viamericas-datalake-dev-us-east-1-283731589572-stage/intermediate_comision_agent_modo_pago_grupo"
      StateMachineName: "sm_stage_intermediate_comision_agent_modo_pago_grupo"
    IntermediateVcwMoneyordersSales:
        JobName: "gj_stage_intermediate_vcw_moneyorders_sales"
        ScriptLocation: "s3://viamericas-datalake-dev-us-east-1-283731589572-glue-jobs/stage/intermediate/gjdev_stage_intermediate_vcw_moneyorders_sales_glue_script.py"
        CrawlerName: "crw_stage_intermediate_vcw_moneyorders_sales"
        Path: "s3://viamericas-datalake-dev-us-east-1-283731589572-stage/intermediate_vcw_moneyorders_sales"
        StateMachineName: "sm_stage_intermediate_vcw_moneyorders_sales"
    IntermediateVcwSalesProducts:
      JobName: "gj_stage_intermediate_vcw_sales_products"
      ScriptLocation: "s3://viamericas-datalake-dev-us-east-1-283731589572-glue-jobs/stage/intermediate/gjdev_stage_intermediate_vcw_sales_products_glue_script.py"
      CrawlerName: "crw_stage_intermediate_vcw_sales_products"
      Path: "s3://viamericas-datalake-dev-us-east-1-283731589572-stage/intermediate_vcw_sales_products"
      StateMachineName: "sm_stage_intermediate_vcw_sales_products"
    IntermediateBranch:
        JobName: "gj_stage_intermediate_branch"
        ScriptLocation: "s3://viamericas-datalake-dev-us-east-1-283731589572-glue-jobs/stage/intermediate/gjdev_stage_intermediate_branch_glue_script.py"
        CrawlerName: "crw_stage_intermediate_branch"
        Path: "s3://viamericas-datalake-dev-us-east-1-283731589572-stage/intermediate_branch"
        StateMachineName: "sm_stage_intermediate_branch"
    IntermediateSfSafeTransactions:
      JobName: "gj_stage_intermediate_sf_safe_transactions"
      ScriptLocation: "s3://viamericas-datalake-dev-us-east-1-283731589572-glue-jobs/stage/intermediate/gjdev_stage_intermediate_sf_safe_transactions_glue_script.py"
      CrawlerName: "crw_stage_intermediate_sf_safe_transactions"
      Path: "s3://viamericas-datalake-dev-us-east-1-283731589572-stage/intermediate_sf_safe_transactions"
      StateMachineName: "sm_stage_intermediate_sf_safe_transactions"

Parameters:
  # Glue Job
  # The name of the job to be created
  StateFunctionNames:
    Type: CommaDelimitedList
    Default: "IntermediateReceiver, IntermediateCheckTable, IntermediateSender, IntermediateAccountingSubmitTransaction, IntermediateVcwBillPaymentsales, IntermediateComisionAgentModoPagoGrupo, IntermediateVcwMoneyordersSales, IntermediateVcwSalesProducts, IntermediateBranch, IntermediateSfSafeTransactions"
  VIAIAMRoleArn:
    Type: String
    Default: arn:aws:iam::283731589572:role/GlueRolFullAccess
  VIACrawlerRolArn:
    Type: String
    Default: arn:aws:iam::283731589572:role/sdlf-lakeformation-admin
  VIADatabaseName:
    Type: String
    Default: stage
  # The S3 path where the script for this job is located
  VIAConnectionName:
    Type: String
    Default: via-database-connection
  # State machine
  VIARolStateMachineArn:
    Type: String
    Default: arn:aws:iam::283731589572:role/cf-aws-glue-sf-run

  VIAStateMachineType:
    Type: String
    Default: STANDARD

  # SNS
  VIASnsTopicArn:
    Type: String
    Default: arn:aws:sns:us-east-1:283731589572:sdlf-email-notifications

  # External python function
  ViaExternalPythonFunctions:
    Type: String
    Default: s3://viamericas-datalake-dev-us-east-1-283731589572-glue-jobs/Codes.zip

  Environment:
    Type: String
    Default: dev
  
#
#
# Resources section defines metadata for the Data Catalog
Resources:
  # Create jobs to run script which accesses JDBC viamericas db via a connection and write to S3 file as parquet.
  Fn::ForEach::GlueJobIntermediate:
    - GlueJobItem # identificador
    - !Ref StateFunctionNames # lista de los objetos a iterar
    - Job${GlueJobItem}: 
        Type: AWS::Glue::Job
        Properties:
          Role: !Ref VIAIAMRoleArn
          Connections:
            Connections:
              - !Ref VIAConnectionName
          #MaxRetries: Double
          Description: "Job created with CloudFormation using script template_stage.yaml"
          #LogUri: String
          Command:
            Name: "glueetl"
            PythonVersion: "3"
            ScriptLocation:
              Fn::FindInMap: ["GlueObjects", !Ref GlueJobItem, "ScriptLocation"]
          NumberOfWorkers: 5
          GlueVersion: "4.0"
          DefaultArguments:
            "--conf": !Sub "spark.shuffle.glue.s3ShuffleBucket=s3://viamericas-datalake-${Environment}-us-east-1-${AWS::AccountId}-athena/gluetmp/"
            "----write-shuffle-files-to-s3": "true"
            "--write-shuffle-spills-to-s3": "true"
            "--additional-python-modules": "awswrangler==2.14.0"
            '--enable-metrics': 'true'
            '--enable-glue-datacatalog': 'true'
            '--extra-py-files': !Ref ViaExternalPythonFunctions
          Tags:
            "map-migrated": "mig42454"
          ExecutionProperty:
            MaxConcurrentRuns: 1
          Name:
            Fn::FindInMap: ["GlueObjects", !Ref GlueJobItem, "JobName"]
          WorkerType: "G.1X"
          Timeout: 330

  Fn::ForEach::GlueCrawlers:
    - GlueCrawlerItem
    - !Ref StateFunctionNames
    - Crawler${GlueCrawlerItem}:
        Type: AWS::Glue::Crawler
        Properties:
          Name:
            Fn::FindInMap: ["GlueObjects", !Ref GlueCrawlerItem, "CrawlerName"]
          Role: !Ref VIACrawlerRolArn
          #Classifiers: none, use the default classifier
          Description: "AWS Glue crawler to crawl viamericas stage data"
          #Schedule: none, use default run-on-demand
          DatabaseName: !Ref VIADatabaseName
          Targets:
            S3Targets:
              # Private S3 path with the viamericas data
              - Path:
                  Fn::FindInMap: ["GlueObjects", !Ref GlueCrawlerItem, "Path"]
              - ConnectionName: !Ref VIAConnectionName
          Tags:
            "map-migrated": "mig42454"
          TablePrefix: ""
          RecrawlPolicy:
            RecrawlBehavior: "CRAWL_EVERYTHING"
          SchemaChangePolicy:
            UpdateBehavior: "UPDATE_IN_DATABASE"
            DeleteBehavior: "DEPRECATE_IN_DATABASE"
          Configuration: '{"Version":1.0,"CreatePartitionIndex":true}'
  # State machines
  Fn::ForEach::StateMachinesIncremental:
    - StateMachineItem
    - !Ref StateFunctionNames
    - StateMachine${StateMachineItem}:
        Type: AWS::StepFunctions::StateMachine
        Properties:
          Definition:
            {
              "Comment": "This executes a glue job that writes to a S3 bucket and depends if the table exists or not, will add the new partition into the table or will create it.",
              "StartAt": "RunGlueJob",
              "States":
                {
                  "RunGlueJob":
                    {
                      "Parameters":
                        {
                          "JobName":
                            !FindInMap [
                              "GlueObjects",
                              !Ref StateMachineItem,
                              "JobName",
                            ],
                        },
                      "Resource": "arn:aws:states:::glue:startJobRun.sync",
                      "Type": "Task",
                      "Retry": [
                        {
                          "ErrorEquals": [
                            "States.ALL"
                          ],
                          "BackoffRate": 2,
                          "IntervalSeconds": 180,
                          "MaxAttempts": 3
                        }
                      ],
                      "Catch":
                        [
                          {
                            "ErrorEquals": ["States.ALL"],
                            "Next": "SNS Publish",
                          },
                        ],
                      "End": true,
                    },
                  "SNS Publish":
                    {
                      "Type": "Task",
                      "Resource": "arn:aws:states:::sns:publish",
                      "Parameters":
                        { 
                          "TopicArn": !Ref VIASnsTopicArn, 
                          "Message.$": "$" 
                        },
                      "Next": "Fail"
                    },
                    "Fail": 
                    {
                      "Type": "Fail"
                    }
                },
            }
          #DefinitionSubstitutions:
          #  Key: Value
          #LoggingConfiguration:
          #  LoggingConfiguration
          RoleArn: !Ref VIARolStateMachineArn
          StateMachineName:
            Fn::FindInMap:
              ["GlueObjects", !Ref StateMachineItem, "StateMachineName"]
          StateMachineType: !Ref VIAStateMachineType
          Tags:
            - Key: "map-migrated"
              Value: "mig42454"
            #  - TagsEntry
            #TracingConfiguration:
            #  TracingConfiguration